console.log("1. Crear un archivo de texto")
console.log("2. Añadir al archivo al final la extensión .html")
console.log("3. Editar el archivo html con un editor de texto")
console.log("4. Crear el DOCTYPE")
console.log("5. Crear la etiqueta <html> bajo el DOCTYPE")
console.log("6. Crear la etiqueta <head>")
console.log("7. Crear la etiqueta <body>")
console.log("8. Dentro de la etiqueta <head>, crear una etiqueta <title>")
console.log("9. Guardar el archivo")
console.log("10. Ya está creado el archivo html")